# Site settings
title: Ilia Kuhnovets
name: Ilia Kuhnovets

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Linkedin
   url: https://www.linkedin.com/in/ilia-kuhnovets-0819051ba/
 - title: GitHub
   url: https://github.com/Ilia93
 - title: CodeWars
   url: https://www.codewars.com/users/Cicero93

#Any buzzword skills you want to include
skills:
 - Java
 - Android
 - Git

#Work experience is required
roles:
 - title: Topographer
   start: 2016
   end: Ongoing
   employer: Ministry of Defence
 
#Education is required
education:
   date: 2016
   subject: GIS-specialist in military 
   university: BSU

intro: |
I am a beginner android developer, whos want to be a great specialist in adnroid programming. I have worked on the Android for a one year and i really enjoy with building mobile apps.<br/><br/>

additionalinfo: |
   <strong>Android</strong>: I have one year of experience in Android study projects. I have worked with Retrofit, Room. <br/><br/>
   <strong>English</strong>  I could speak in English for differenet subjects, but not like a native speaker<br/><br/>
