# Site settings
title: Ilia Kuhnovets
name: Ilia Kuhnovets

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Linkedin
   url: https://www.linkedin.com/in/ilia-kuhnovets-0819051ba/
 - title: GitHub
   url: https://github.com/Ilia93
 - title: CodeWars
   url: https://www.codewars.com/users/Cicero93

#Any buzzword skills you want to include
skills:
 - Java
 - Android
 - Git

#Work experience is required
roles:
 - title: Topographer
   start: 2016
   end: Ongoing
   employer: Ministry of Defence
 
#Education is required
education:
   date: 2016
   subject: GIS-specialist in military 
   university: BSU

intro: |
  I am an engineer with 15 years experience working in technology. I have primarily worked on the JVM, but have worked across a broad range of technologies thereon: Java, Groovy, Android, Coldfusion and most recently Scala. As well as spending a reasonable amount of time building applications for the web, which has given me an exposure to a range of javascript technologies over the years, through jQuery, extjs, knockout, backbone and most recently to React. <br/><br/>
  I enjoy building interesting products, with a good Product Management focus and a good emphasis on good engineering principles and clean code (having worked across differing languages on the JVM, I recognise that good code is contextual).<br/><br/>
  I have worked in large scale consultancy roles across Europe as well as a mix of startup experience (including one that was acquired) and I am currently the Chief Technology Officer at a legal-tech startup called <a href="https://www.basementcrowd.com" target="_blank">Basement Crowd</a> where we are building innovative products to serve the legal industry.


additionalinfo: |
   <strong>Android</strong>: I have one year of experience in Android study projects. I have worked with Retrofit, Room. <br/><br/>
   <strong>English</strong>  I could speak in English for differenet subjects, but not like a native speaker<br/><br/>
